# Generated by Django 5.0.7 on 2024-07-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_feedback_product_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('powder', 'Powder'), ('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('sweets', 'Sweets'), ('chats', 'Chats')], max_length=6, null=True),
        ),
    ]
